/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  accessToken: string | null;
  accessTokenExpiresAt: Timestamp | null;
  accountId: string;
  createdAt: Generated<Timestamp>;
  id: string;
  idToken: string | null;
  password: string | null;
  providerId: string;
  refreshToken: string | null;
  refreshTokenExpiresAt: Timestamp | null;
  scope: string | null;
  updatedAt: Timestamp;
  userId: string;
}

export interface Allowlist {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  addedById: string | null;
}

export interface Interview {
  createdAt: Generated<Timestamp>;
  hostId: string;
  endTime: Timestamp | null;
  id: Generated<number>;
  isInstant: Generated<boolean>;
  sessionId: Generated<string>;
  startTime: Timestamp;
  updatedAt: Generated<Timestamp>;
}

export interface InterviewInvite {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<number>;
  interviewId: number;
  isInterviewer: Generated<boolean>;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  ipAddress: string | null;
  token: string;
  updatedAt: Timestamp;
  userAgent: string | null;
  userId: string;
}

export interface User {
  createdAt: Generated<Timestamp>;
  email: string;
  emailVerified: boolean;
  id: string;
  image: string | null;
  name: string;
  updatedAt: Generated<Timestamp>;
}

export interface Verification {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: string;
  identifier: string;
  updatedAt: Generated<Timestamp>;
  value: string;
}

export interface DB {
  account: Account;
  allowlist: Allowlist;
  interview: Interview;
  interviewInvite: InterviewInvite;
  session: Session;
  user: User;
  verification: Verification;
}
