/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Interview {
  createdAt: Generated<Timestamp>;
  creatorId: string;
  endTime: Timestamp;
  id: Generated<number>;
  sessionName: Generated<string>;
  startTime: Timestamp;
  updatedAt: Generated<Timestamp>;
}

export interface InterviewInvite {
  email: string;
  id: Generated<number>;
  interviewId: number;
}

export interface DB {
  interview: Interview;
  interviewInvite: InterviewInvite;
}
