version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 30
      semver-major-days: 30
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-minor', 'version-update:semver-patch']
    groups:
      eslint-config:
        patterns:
          - '@antfu/eslint-config'
          - '@eslint-react/eslint-plugin'
          - 'eslint-plugin*'

  - package-ecosystem: uv
    directory: /electron/python/
    schedule:
      interval: monthly
    cooldown:
      default-days: 30
      semver-major-days: 30
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-minor', 'version-update:semver-patch']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 30
