version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      update-types:
        - major
      cooldown:
        semver-major-days: 30

  - package-ecosystem: uv
    directory: /electron/python/
    schedule:
      interval: monthly
      update-types:
        - major
      cooldown:
        semver-major-days: 30
