/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authenticatedHomeRouteImport } from './routes/(authenticated)/home'
import { Route as authenticatedEndRouteImport } from './routes/(authenticated)/end'
import { Route as authenticatedInterviewRouteRouteImport } from './routes/(authenticated)/interview/route'
import { Route as authenticatedInterviewIndexRouteImport } from './routes/(authenticated)/interview/index'
import { Route as authenticatedInterviewIdRouteImport } from './routes/(authenticated)/interview/$id'
import { Route as authenticatedInterviewPrejoinIndexRouteImport } from './routes/(authenticated)/interview/prejoin/index'
import { Route as authenticatedInterviewPrejoinIdRouteImport } from './routes/(authenticated)/interview/prejoin/$id'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedHomeRoute = authenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedEndRoute = authenticatedEndRouteImport.update({
  id: '/end',
  path: '/end',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedInterviewRouteRoute =
  authenticatedInterviewRouteRouteImport.update({
    id: '/interview',
    path: '/interview',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedInterviewIndexRoute =
  authenticatedInterviewIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => authenticatedInterviewRouteRoute,
  } as any)
const authenticatedInterviewIdRoute =
  authenticatedInterviewIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => authenticatedInterviewRouteRoute,
  } as any)
const authenticatedInterviewPrejoinIndexRoute =
  authenticatedInterviewPrejoinIndexRouteImport.update({
    id: '/prejoin/',
    path: '/prejoin/',
    getParentRoute: () => authenticatedInterviewRouteRoute,
  } as any)
const authenticatedInterviewPrejoinIdRoute =
  authenticatedInterviewPrejoinIdRouteImport.update({
    id: '/prejoin/$id',
    path: '/prejoin/$id',
    getParentRoute: () => authenticatedInterviewRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof authenticatedRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/interview': typeof authenticatedInterviewRouteRouteWithChildren
  '/end': typeof authenticatedEndRoute
  '/home': typeof authenticatedHomeRoute
  '/interview/$id': typeof authenticatedInterviewIdRoute
  '/interview/': typeof authenticatedInterviewIndexRoute
  '/interview/prejoin/$id': typeof authenticatedInterviewPrejoinIdRoute
  '/interview/prejoin': typeof authenticatedInterviewPrejoinIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof authenticatedRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/end': typeof authenticatedEndRoute
  '/home': typeof authenticatedHomeRoute
  '/interview/$id': typeof authenticatedInterviewIdRoute
  '/interview': typeof authenticatedInterviewIndexRoute
  '/interview/prejoin/$id': typeof authenticatedInterviewPrejoinIdRoute
  '/interview/prejoin': typeof authenticatedInterviewPrejoinIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/(authenticated)/interview': typeof authenticatedInterviewRouteRouteWithChildren
  '/(authenticated)/end': typeof authenticatedEndRoute
  '/(authenticated)/home': typeof authenticatedHomeRoute
  '/(authenticated)/interview/$id': typeof authenticatedInterviewIdRoute
  '/(authenticated)/interview/': typeof authenticatedInterviewIndexRoute
  '/(authenticated)/interview/prejoin/$id': typeof authenticatedInterviewPrejoinIdRoute
  '/(authenticated)/interview/prejoin/': typeof authenticatedInterviewPrejoinIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/interview'
    | '/end'
    | '/home'
    | '/interview/$id'
    | '/interview/'
    | '/interview/prejoin/$id'
    | '/interview/prejoin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/end'
    | '/home'
    | '/interview/$id'
    | '/interview'
    | '/interview/prejoin/$id'
    | '/interview/prejoin'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/sign-in'
    | '/(authenticated)/interview'
    | '/(authenticated)/end'
    | '/(authenticated)/home'
    | '/(authenticated)/interview/$id'
    | '/(authenticated)/interview/'
    | '/(authenticated)/interview/prejoin/$id'
    | '/(authenticated)/interview/prejoin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/home': {
      id: '/(authenticated)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof authenticatedHomeRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/end': {
      id: '/(authenticated)/end'
      path: '/end'
      fullPath: '/end'
      preLoaderRoute: typeof authenticatedEndRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/interview': {
      id: '/(authenticated)/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof authenticatedInterviewRouteRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/interview/': {
      id: '/(authenticated)/interview/'
      path: '/'
      fullPath: '/interview/'
      preLoaderRoute: typeof authenticatedInterviewIndexRouteImport
      parentRoute: typeof authenticatedInterviewRouteRoute
    }
    '/(authenticated)/interview/$id': {
      id: '/(authenticated)/interview/$id'
      path: '/$id'
      fullPath: '/interview/$id'
      preLoaderRoute: typeof authenticatedInterviewIdRouteImport
      parentRoute: typeof authenticatedInterviewRouteRoute
    }
    '/(authenticated)/interview/prejoin/': {
      id: '/(authenticated)/interview/prejoin/'
      path: '/prejoin'
      fullPath: '/interview/prejoin'
      preLoaderRoute: typeof authenticatedInterviewPrejoinIndexRouteImport
      parentRoute: typeof authenticatedInterviewRouteRoute
    }
    '/(authenticated)/interview/prejoin/$id': {
      id: '/(authenticated)/interview/prejoin/$id'
      path: '/prejoin/$id'
      fullPath: '/interview/prejoin/$id'
      preLoaderRoute: typeof authenticatedInterviewPrejoinIdRouteImport
      parentRoute: typeof authenticatedInterviewRouteRoute
    }
  }
}

interface authenticatedInterviewRouteRouteChildren {
  authenticatedInterviewIdRoute: typeof authenticatedInterviewIdRoute
  authenticatedInterviewIndexRoute: typeof authenticatedInterviewIndexRoute
  authenticatedInterviewPrejoinIdRoute: typeof authenticatedInterviewPrejoinIdRoute
  authenticatedInterviewPrejoinIndexRoute: typeof authenticatedInterviewPrejoinIndexRoute
}

const authenticatedInterviewRouteRouteChildren: authenticatedInterviewRouteRouteChildren =
  {
    authenticatedInterviewIdRoute: authenticatedInterviewIdRoute,
    authenticatedInterviewIndexRoute: authenticatedInterviewIndexRoute,
    authenticatedInterviewPrejoinIdRoute: authenticatedInterviewPrejoinIdRoute,
    authenticatedInterviewPrejoinIndexRoute:
      authenticatedInterviewPrejoinIndexRoute,
  }

const authenticatedInterviewRouteRouteWithChildren =
  authenticatedInterviewRouteRoute._addFileChildren(
    authenticatedInterviewRouteRouteChildren,
  )

interface authenticatedRouteRouteChildren {
  authenticatedInterviewRouteRoute: typeof authenticatedInterviewRouteRouteWithChildren
  authenticatedEndRoute: typeof authenticatedEndRoute
  authenticatedHomeRoute: typeof authenticatedHomeRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedInterviewRouteRoute:
    authenticatedInterviewRouteRouteWithChildren,
  authenticatedEndRoute: authenticatedEndRoute,
  authenticatedHomeRoute: authenticatedHomeRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
