minimumReleaseAge: 4320

shellEmulator: true

trustPolicy: no-downgrade

packages:
  - client
  - server
  - shared
  - electron

catalog:
  better-auth: 1.4.17
  zod: 4.3.6

onlyBuiltDependencies:
  - electron
  - electron-winstaller
  - esbuild
  - sharp
  - workerd
