import { z } from 'zod'

export const TranscriptMessage = z.object({
  text: z.string(),
  status: z.enum(['final', 'partial']),
})

export const InterviewerNotification = z.object({
  hint: z.array(z.string()).default([]),
})

export const IntervieweeNotification = z.object({
  hint: z.array(z.string()).default([]),
  fillerCount: z.number().default(0),
  wordCount: z.number().default(0),
  newTopic: z.boolean().default(false),
  offTopic: z.boolean().default(false),
})

export const DevIsJohnDoNotUseThisMessage = z.object({
  isJohn: z.boolean(),
  isInterviewer: z.boolean(),
})

export const WebSocketMessage = z.discriminatedUnion('type', [
  z.object({ type: z.literal('transcript'), payload: TranscriptMessage }),
  z.object({ type: z.literal('interviewerNotification'), payload: InterviewerNotification }),
  z.object({ type: z.literal('intervieweeNotification'), payload: IntervieweeNotification }),
  z.object({ type: z.literal('ping') }),
  z.object({ type: z.literal('pong') }),
  z.object({ type: z.literal('devIsJohnDoNotUseThis'), payload: DevIsJohnDoNotUseThisMessage }),
  // reasoning text generated by the AI system, sent before the JSON payload
  z.object({ type: z.literal('reasoning'), payload: z.string() }),
  // transcript text broadcast to all clients (formatted as "[role] name: text")
  z.object({ type: z.literal('broadcastTranscript'), payload: z.string() }),
  z.object({ type: z.literal('resetMessages') }),
])

export type WebSocketMessage = z.infer<typeof WebSocketMessage>
export type TranscriptMessage = z.infer<typeof TranscriptMessage>
export type InterviewerNotification = z.infer<typeof InterviewerNotification>
export type IntervieweeNotification = z.infer<typeof IntervieweeNotification>
export type DevIsJohnDoNotUseThisMessage = z.infer<typeof DevIsJohnDoNotUseThisMessage>
