import { z } from 'zod'

export const TranscriptMessage = z.object({
  text: z.string(),
  status: z.enum(['final', 'partial']),
})

export const NotificationMessage = z.object({
  hint: z.array(z.string()).default([]),
  fillerCount: z.number().default(0),
  wordCount: z.number().default(0),
  newTopic: z.boolean().default(false),
  offTopic: z.boolean().default(false),
})

export const DevIsJohnDoNotUseThisMessage = z.object({
  isJohn: z.boolean(),
  isInterviewer: z.boolean(),
})

export const WebSocketMessage = z.discriminatedUnion('type', [
  z.object({ type: z.literal('transcript'), payload: TranscriptMessage }),
  z.object({ type: z.literal('notification'), payload: NotificationMessage }),
  z.object({ type: z.literal('ping') }),
  z.object({ type: z.literal('pong') }),
  z.object({ type: z.literal('devIsJohnDoNotUseThis'), payload: DevIsJohnDoNotUseThisMessage }),
  // reasoning text generated by the AI system, sent before the JSON payload
  z.object({ type: z.literal('reasoning'), payload: z.string() }),
])

export type WebSocketMessage = z.infer<typeof WebSocketMessage>
export type TranscriptMessage = z.infer<typeof TranscriptMessage>
export type NotificationMessage = z.infer<typeof NotificationMessage>
export type DevIsJohnDoNotUseThisMessage = z.infer<typeof DevIsJohnDoNotUseThisMessage>
