name: Cloudflare Deploy

on: [workflow_call]

jobs:
  # only deploy when files in server/ change
  check-server-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            changed:
              - 'server/**'
              - 'shared/**'
              - .github/workflows/deploy-cloudflare.yml

  deploy:
    needs: check-server-changes
    if: needs.check-server-changes.outputs.changed == 'true'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm
      - name: Install dependencies
        run: pnpm --filter @webmoti-employ/server install:deploy

      - name: Build & Deploy Worker
        uses: cloudflare/wrangler-action@v3
        with:
          workingDirectory: server
          command: deploy --minify
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
